[project]
name = "iaf-task"
version = "0.1.0"
description = "Inverse Autoregressive Flow"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "scikit-learn>=1.6.1",
    "torch>=2.8.0",
]
